HRApp/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [

    url(r'^RegisterSME$', views.register_sme, name='RegisterSME'),
    url(r'^RegisterHRM$',views.register_hrm,name='RegisterHRM'),
    url(r'^RegisterHRP$',views.register_hrp,name='RegisterHRP'),
    url(r'^application$',views.application,name='ViewApplication'),
    url(r'^CreateCompany$',views.create_company_view,name='CreateCompany'),
    url(r'^CreateCategory$',views.create_category_view,name='CreateCategory'),
    url(r'^PostJob$',views.post_job_view,name='PostJob'),
    url(r'^register$',views.register_view,name='register'),
    url(r'^logout$',views.logout_view,name='logout'),
    url(r'^login$',views.login_view,name='login'),
    url(r'^$',views.index,name='index'),
    url(r'^apply$', views.apply, name='ApplyJob'),
    url(r'^apply/(?P<job>[0-9]+)$',views.apply_job,name='ApplyJob'),
    url(r'^application/(?P<job>[0-9]+)$',views.get_all_apply,name='GetAllApply'),
    url(r'^rate$', views.rate_all_apply, name='RateAllApply'),
    url(r'^rate/(?P<var_apply>[0-9]+)$',views.rate_apply,name='RateApply'),
    url(r'^GetTopFive$',views.get_top_five,name='GetTopFive'),
    url(r'^ApiJson',views.api_json,name='ApiJson'),
]

HRManage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('HRApp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HRApp/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.


class UserType(models.Model):
    user_type = models.CharField(max_length=3, default='A')
    user = models.ForeignKey(User)


class Category(models.Model):
    name = models.CharField(max_length=16)
    description = models.TextField(default='this is category disc')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'categories'


class Company (models.Model):
    name = models.CharField(max_length=32)
    description = models.TextField()
    location = models.CharField(max_length=128)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Job(models.Model):
    title = models.CharField(max_length=32)
    description = models.TextField()
    category = models.ForeignKey(Category)
    company = models.ForeignKey(Company)
    location = models.CharField(max_length=128)
    salary = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Apply(models.Model):
    description = models.TextField()
    document = models.FileField(upload_to='media')
    job = models.ForeignKey(Job)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    uploaded_at = models.DateTimeField(auto_now_add=True)


class RateApply(models.Model):
    rate = models.PositiveIntegerField(default=1, validators=[MaxValueValidator(5), MinValueValidator(1)])
    comment = models.TextField()
    sme = models.ForeignKey(settings.AUTH_USER_MODEL)
    apply = models.ForeignKey(Apply)


class InterviewCall(models.Model):
    apply = models.ForeignKey(Apply)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>

        <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}">
        <link rel="stylesheet" href="{% static "font-awesome/css/font-awesome.min.css" %}">

		<!-- Google Fonts -->
		<link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static "style.css" %}">
		<title>{% block title%}{% endblock %}</title>
	</head>
	<body>
		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/"><i class="fa fa-twitter" aria-hidden="true"></i>Brand</a>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
                        {% block menu %}{% endblock %}
					</ul>
				</div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
		</nav>

        {% block main%}{% endblock %}

        <script src="{% static "js/jquery.min.js" %}"></script>
        <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
        <script src="{% static "js/script.js" %}"></script>

	</body>
</html>

templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title%}
    {{ title }}
{% endblock %}
{% block menu %}
    {% if title == "Job Feed" %}
        <li><a href="/login">Login</a></li>
        <li><a href="/register">Register</a></li>
    {% endif %}
{% endblock %}
{% block main%}
<div class="container">
    <div class="row main">
        <div class="panel-heading">
           <div class="panel-title text-center">
                <h1 class="title">{{ title }}</h1>
                <hr />
            </div>
        </div>

        {% if app %}
            <div class="row">
                <div class="col-md-12">
                    <h5 class="mb-1">{{ app.job.title }}</h5>
                    <small>{{ app.job.created_at }}</small>

                    <p class="mb-1">{{ app.job.description }}</p>
                    <small>{{ app.job.category }}</small> By <small>{{ app.job.company }}</small>
                </div>
                <div class="col-md-12">
                    <span>User Perposel</span>
                    <p class="mb-1">{{ app.description }}</p>
                    <a href="{{ app.document.url }}"><span class="glyphicon-class">glyphicon glyphicon-file</span></a>
                </div>
            </div>
        {% endif %}
        {% if job %}
            <div class="row">
                <div class="col-md-12">
                    <h5 class="mb-1">{{ job.title }}</h5>
                    <small>{{ job.created_at }}</small>

                    <p class="mb-1">{{ job.description }}</p>
                    <small>{{ job.category }}</small> By <small>{{ job.company }}</small>
                </div>
            </div>
        {% endif %}
        <div class="main-login main-center">
            <form class="form-horizontal" method="POST"
                    {% if job %}
                        enctype="multipart/form-data" data-ajax="false"
                    {% endif %}>
                {% if title == "Rate Application" %}
                    <div id="div_id_comment" class="form-group">
                        <label for="id_comment" class="control-label  requiredField">Rate<span class="asteriskField">*</span> </label>
                        <div class="controls ">
                            <div id="stars" class="starrr"></div>
                        </div>
                    </div>
                {% endif %}
                {% csrf_token %}
                {{ form | crispy }}

                <button type="submit" class="btn btn-primary btn-block">{{ title }}</button>

                {% if title == "Login" %}
                    <div class="login-register">
                        <a href="/register">Register</a>
                        or
                        <a href="/">Forget Password</a>
                    </div>
                {% endif %}
                {% if title == "Register" %}
                    <div class="login-register">
                        <a href="/login">Login</a>
                    </div>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title%}
    {{ title }}
{% endblock %}
{% block menu %}
    {% if title == "Job Feed" %}
        <li><a href="/login">Login</a></li>
        <li><a href="/register">Register</a></li>
    {% else %}
        {% if menu %}
            {% for m in menu %}
                <li><a href="/{{ m.1 }}">{{ m.0 }}</a></li>
            {% endfor %}
        {% endif %}
        <li><a href="/logout">Logout</a></li>
    {% endif %}
{% endblock %}
{% block main%}
    <div class="container">
        <div class="panel-heading">
           <div class="panel-title text-center">
                <h1 class="title">{{ title }}</h1>
                <hr />
            </div>
        </div>
        <div class="row">
            <div class="list-group">
                {% for job in jobs %}
                    <a
                            {% if title == "Post CV" %}
                                href="/apply/{{ job.id }}"
                            {% elif title == "Application By Job" %}
                                href="/application/{{ job.id }}"
                            {% endif %}
                            class="list-group-item list-group-item-action flex-column align-items-start">
                        <div class="justify-content-between">
                            <h5 class="mb-1">{{ job.title }}</h5>
                            <small>{{ job.created_at }}</small>
                        </div>
                        <p class="mb-1">{{ job.description }}</p>
                        <small>{{ job.category }}</small> By <small>{{ job.company }}</small>
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/listApps.html
{% extends "base.html" %}
{% block title%}
    {{ title }}
{% endblock %}
{% block main%}
    <div class="container">
        <div class="panel-heading">
           <div class="panel-title text-center">
                <h1 class="title">{{ title }}</h1>
                <hr />
            </div>
        </div>
        <div class="row">
            <div class="list-group">
                <ul class="listrap">
                    {% if type == "HRP" or type == "HRM" %}
                    <form id="ajaxFormSubmit" method="post" onsubmit="do_something()">
                        {% csrf_token %}
                    {% endif %}
                    {% for app in list %}
                        <li class="col-md-6 non_active">
                            {% if type == "SME" or type == "HRM" %}
                            <a href="/rate/{{ app.id }}">
                            {% endif %}
                                <div class="listrap-toggle ">
                                    <span></span>
                                    <img src="http://lorempixel.com/60/60/people/?v=1" class="img-circle" />
                                    <input class="userID" type="hidden" name="userID[]" value="{{ app.id }}">
                                </div>
                                <strong>{{ app.user.first_name }} {{ app.user.last_name }}</strong>
                                <p class="mb-1">{{ app.description }}</p>
                                <a href="{{ app.document.url }}"><span class="glyphicon-class">glyphicon glyphicon-file</span></a>
                            {% if type == "SME" or type == "HRM" %}
                                <div id="stars1" class="starrr"></div>
                            </a>
                            {% endif %}
                        </li>
                    {% endfor %}
                    {% if type == "HRP" or type == "HRM" %}
                    <div class="col-md-12"><button type="submit" class="btn btn-primary btn-block">{{ title }}</button></div>
                    </form>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/product.html
<html>
    <head>
        <title>Welcome</title>
    </head>
    <body>
        <h1>Product Detail</h1>
        <h3>{{ product.name }}</h3>
        <h4>{{ product.price }}</h4>
        <h5>{{ product.category }}</h5>
        <p>{{ product.description }}</p>
    </body>
</html>

templates/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title%}
    {{ title }}
{% endblock %}
{% block menu %}
    {% if menu %}
        {% for m in menu %}
            <li><a href="/{{ m.1 }}">{{ m.0 }}</a></li>
        {% endfor %}
    {% endif %}
    <li><a href="/logout">Logout</a></li>
{% endblock %}
{% block main%}
<div class="container">
    <div class="row main">
        <div class="panel-heading">
           <div class="panel-title text-center">
                <h1 class="title">{{ title }}</h1>
                <hr />
            </div>
        </div>
        <div class="main-login main-center">
            <p><span>Username:<bold>{{ user.username }}</bold></span></p>
            <p><span>First Name:<bold>{{ user.first_name }}</bold></span></p>
            <p><span>Last Name:<bold>{{ user.last_name }}</bold></span></p>
            <p><span>Email:<bold>{{ user.email }}</bold></span></p>
            <p><span>User Type:<bold>{{ type }}</bold></span></p>
        </div>
    </div>
</div>
{% endblock %}

templates/rateApps.html
{% extends "base.html" %}
{% block title%}
    {{ title }}
{% endblock %}
{% block main%}
    <div class="container">
        <div class="panel-heading">
           <div class="panel-title text-center">
                <h1 class="title">{{ title }}</h1>
                <hr />
            </div>
        </div>
        <div class="row">
            <div class="list-group">
                <ul class="listrap">
                    {% for app in list %}
                        <li class="col-md-6">
                            <a href="rate/{{ app.id }}">
                                <div class="listrap-toggle">
                                    <span></span>
                                    <img src="http://lorempixel.com/60/60/people/?v=1" class="img-circle" />
                                </div>
                                <strong>{{ app.user.first_name }} {{ app.user.last_name }}</strong>
                                <h5 class="mb-1">{{ app.description }}</h5>
                                <p class="mb-1"><a href="{{ app.document.url }}">{{ app.document }}</a></p>
                                <div id="stars1" class="starrr"></div>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block title%}
    {{ title }}
{% endblock %}
{% block main%}
    <div class="container">
        <div class="panel-heading">
           <div class="panel-title text-center">
                <h1 class="title">{{ title }}</h1>
                <hr />
            </div>
        </div>
        <div class="row">
            <div class="list-group">
                {% for job in types %}
                    <a href="/apply/{{ job.id }}" class="list-group-item list-group-item-action flex-column align-items-start">
                        <div class="justify-content-between">
                            <h5 class="mb-1">{{ job.user_type }}</h5>
                        </div>
                        <p class="mb-1">{{ job.user.name }}</p>
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}